[project]
name = "giassi-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.10.6",
    "mcp[cli]>=1.12.2",
    "mcpo>=0.0.16",
    "playwright>=1.54.0",
    "pyyaml>=6.0.2",
    "uvicorn>=0.35.0",
]
